spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue?useUnicode&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
